const mapBitmap = [
  "........oo..............",
  ".......oooo.............",
  "......ooooo.............",
  "......oooo..............",
  "....oooooooo............",
  "...ooooooooUUUoo....oo..",
  "..oooooooUUUUUoooo.oooo.",
  "..ooooooPPPPUUooooooooo.",
  ".GGooooPPPPPPoooooooo...",
  "GGGGooPPPPPPPCCoo.......",
  "GGGGGoPPPPPPPCCCoo......",
  ".GGGGMMMMMMMPCCCo.......",
  "..GGMMMMMMMMMCCCo.......",
  "....MMMMMMMMMCCoo.......",
  "....MMMMMMMMooooo.......",
  ".....AMMMMoooooo........",
  ".....Aooooooooo.........",
  "......ooooooooo.........",
  "......oooooooo..........",
  "......ooooooo...........",
  ".......oooooo...........",
  ".......ooooo............",
  "........oooo............",
  "........ooo.............",
  ".........oo.............",
  ".........o..............",
];

module.exports = { mapBitmap };
